<a href="https://colab.research.google.com/github/Khang-lee/DEEPLEARNING/blob/main/Buoi1-2_NUMPY%2CPANDA%2CTENSOFLOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY

import numpy as np
import pandas as pd
# --- 3.1. Array 1-chiều ---
#cách 1
# tạo list
my_list = [1, 9, 15, 39]
print('Python list:', my_list)
#chuyển list --> Numpy array
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

#cách 2
a = np.array([1, 9, 15, 39])
print(a)


# --- 3.2. Array 2-chiều ---
c = np.array([(1, 2, 3),
              (4, 5, 6)
             ])
print("--- 3.2 Array 2-chieu ---")
print(c)
print(c.shape)
print(c.dtype)
print("-" * 30)

# --- 3.3. Array 3-chiều ---
d = np.array([
              [[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])
print("--- 3.3 Array 3-chieu ---")
print(d)
print(d.shape)
print("-" * 30)

# --- 3.4. Tạo Array với giá trị ban đầu là 0 hoặc 1 ---
e_zeros = np.zeros((2, 2))
f_ones = np.ones((3, 3))
print("--- 3.4 Array 0 va 1 ---")
print('Zero matrix:\n', e_zeros)
print('One matrix:\n', f_ones)
print("-" * 30)

# 3.5.1. Reshape thay đổi kích thước ma trận
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print("--- 3.5.1 Reshape ---")
print(e)
print(e.shape)

f = e.reshape(3, 2)
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])
print(g)
print(g.shape)

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)
print("-" * 30)

# 3.5.2. Flatten là chuyển array nhiều chiều về 1 chiều
print("--- 3.5.2 Flatten ---")
e_flat = np.array([[1., 2., 3.], [4., 5., 6.]])
f_flat = e_flat.flatten()
print(f_flat)

g_flat = np.array([[[1., 2., 3.], [4., 5., 6.]],
                   [[7., 8., 9.], [10., 11., 12.]]
                  ])
j_flat = g_flat.flatten()
print(j_flat)

# --- 3.6. Thêm dòng dữ liệu với hstack và vstack ---
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)

v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)
print("-" * 30)

# 3.7.1. Sinh mảng số nguyên ngẫu nhiên
a_int = np.random.randint(100, size=(5,))
print('Random 1-D array (int)\n', a_int)

b_int = np.random.randint(100, size=(3, 4))
print('Random 2-D array (int)\n', b_int)

c_int = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array (int)\n', c_int)
print("-" * 30)

# 3.7.2. Sinh mảng số thực [0, 1]
a_rand = np.random.rand(5)
print('Random 1-D array (float)\n', a_rand)

b_rand = np.random.rand(3, 4)
print('Random 2-D array (float)\n', b_rand)
print("-" * 30)

# 3.7.3. Sinh mảng theo phân phối chuẩn Gaussian
a_normal = np.random.normal(5, 0.5, 10)
print('Normal distribution array:\n', a_normal)

# --- 3.7.4. Sinh ngẫu nhiên từ mảng cho trước ---
print("--- 3.7.4 Choice ---")
arr_choice = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
a = np.random.choice(arr_choice)
print('Single random choice:', a)
b = np.random.choice(arr_choice, size=(3, 5))
print('Random 3x5 matrix from choice:\n', b)

# --- 3.8. Thay đổi giá trị của ma trận ---
print("\n--- 3.8 Change Values ---")
A = np.matrix(np.ones((5, 5)))
# Thay đổi hàng thứ 3 (index 2) thành giá trị 2
A[2] = 2
print('Matrix after change:\n', A)

# --- 3.9. Tạo dãy số dãy số ---
print("\n--- 3.9 Range & Linspace ---")
# arange(start, stop, step)
print('Arange (1 to 19):', np.arange(1, 20))
print('Arange step 2:', np.arange(1, 20, 2))

# linspace(start, stop, num) -> Chia đoạn 1-5 thành 10 phần bằng nhau
print('Linspace (1 to 5, 10 parts):\n', np.linspace(1., 5., num=10))

# --- 3.10. Index và Slice (Cắt mảng) ---
print("\n--- 3.10 Index & Slice ---")
data = np.array([(1, 2, 3), (4, 5, 6)])
print('Original Array:\n', data)
print('First row:', data[0])
print('Second column:', data[:, 1]) # Dấu : nghĩa là lấy tất cả các dòng
print('First two values of second row:', data[1, :2])
#tạo mảng array đã chiều
#biến đổi mảng
#ghép kết nối
#khởi tạo ngẫu nhiên
#kiểm tra dạng dtype và shape

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]
--- 3.2 Array 2-chieu ---
[[1 2 3]
 [4 5 6]]
(2, 3)
int64
------------------------------
--- 3.3 Array 3-chieu ---
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
------------------------------
--- 3.4 Array 0 va 1 ---
Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
------------------------------
--- 3.5.1 Reshape ---
[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]
------------------------------
--- 3.5.2 Flatten ---
[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
Horizontal Append
 

In [ ]:
#PANDAS
# --- 6. Cấu trúc dữ liệu 1 chiều ---
import pandas as pd
import numpy as np

# --- 1. TẠO CẤU TRÚC DỮ LIỆU PANDAS ---
print("--- 1. Create DataFrame ---")
# Tạo DataFrame từ Dictionary (kết hợp kiến thức mảng 1-chiều)
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Score': [8.5, 9.0, 7.5, 8.0]
}
df = pd.DataFrame(data_dict)
print("DataFrame vừa tạo:\n", df)

# --- 2. ĐỌC DỮ LIỆU CSV ---
print("\n--- 2. Read CSV ---")
# df_csv = pd.read_csv('your_file.csv')
# print(df_csv.head())

# --- 3. KIỂM TRA THÔNG TIN DỮ LIỆU ---
print("\n--- 3. Data Inspection ---")
print("Kích thước (shape):", df.shape)
print("Kiểu dữ liệu từng cột:\n", df.dtypes)
print("Thông tin thống kê cơ bản:\n", df.describe())

# --- 4. TRUY XUẤT VÀ CẮT DỮ LIỆU (Indexing & Slicing) ---
print("\n--- 4. Indexing & Slicing ---")
# Áp dụng quy tắc Index: giá trị trước dấu ',' là dòng, sau là cột
print("Lấy 2 dòng đầu tiên:\n", df.iloc[:2, :])
print("Lấy cột 'Age':\n", df['Age'])

# --- 5. XỬ LÝ VÀ BIẾN ĐỔI (Sử dụng Numpy bên trong Pandas) ---
print("\n--- 5. Transformation ---")
age_array = df['Age'].values
print("Cột Age chuyển sang Numpy array:", age_array)

# Tính trung bình cộng của cột Score
mean_score = df['Score'].mean()
print("Điểm trung bình:", mean_score)

# Lọc dữ liệu bằng điều kiện (giống np.where)
high_scores = df[df['Score'] > 8.0]
print("Những người có điểm > 8.0:\n", high_scores)

# --- 6. SINH DỮ LIỆU NGẪU NHIÊN CHO DATAFRAME ---
print("\n--- 6. Random DataFrame ---")
# Kết hợp hàm rand và randint để tạo bảng dữ liệu giả lập
random_data = pd.DataFrame(
    np.random.rand(5, 3),
    columns=['Feature_1', 'Feature_2', 'Feature_3']
)
print("DataFrame ngẫu nhiên 5x3:\n", random_data)

#thực hiên các phép toán cơ bản
#hàm thống kê tóm tắt đặc điểm của bộ dữ liệu lớn
#Sắp xếp và tìm kiếm các file dữ liệu lớn
#so sánh mảng

--- 1. Create DataFrame ---
DataFrame vừa tạo:
       Name  Age  Score
0    Alice   25    8.5
1      Bob   30    9.0
2  Charlie   35    7.5
3    David   40    8.0

--- 2. Read CSV ---

--- 3. Data Inspection ---
Kích thước (shape): (4, 3)
Kiểu dữ liệu từng cột:
 Name      object
Age        int64
Score    float64
dtype: object
Thông tin thống kê cơ bản:
              Age     Score
count   4.000000  4.000000
mean   32.500000  8.250000
std     6.454972  0.645497
min    25.000000  7.500000
25%    28.750000  7.875000
50%    32.500000  8.250000
75%    36.250000  8.625000
max    40.000000  9.000000

--- 4. Indexing & Slicing ---
Lấy 2 dòng đầu tiên:
     Name  Age  Score
0  Alice   25    8.5
1    Bob   30    9.0
Lấy cột 'Age':
 0    25
1    30
2    35
3    40
Name: Age, dtype: int64

--- 5. Transformation ---
Cột Age chuyển sang Numpy array: [25 30 35 40]
Điểm trung bình: 8.25
Những người có điểm > 8.0:
     Name  Age  Score
0  Alice   25    8.5
1    Bob   30    9.0

--- 6. Random DataFrame -

In [ ]:
#Tensorflow
import tensorflow as tf
import numpy as np

# --- 3.1. TENSOR 0 CHIỀU (SCALAR) ---
print("--- 3.1. Scalar (0-D Tensor) ---")
# Tạo một hằng số tensor số nguyên
tensor_0d = tf.constant(4)
print("Scalar:", tensor_0d)
print("-" * 30)

# --- 3.2. TENSOR 1 CHIỀU (VECTOR) ---
print("--- 3.2. Vector (1-D Tensor) ---")
# Tạo tensor từ một danh sách
tensor_1d = tf.constant([2.0, 3.0, 4.0])
print("Vector:", tensor_1d)
print("-" * 30)

# --- 3.3. TENSOR 2 CHIỀU (MATRIX) ---
print("--- 3.3. Matrix (2-D Tensor) ---")
tensor_2d = tf.constant([[1, 2], [3, 4], [5, 6]])
print("Matrix:\n", tensor_2d)
print("-" * 30)

# --- 3.4. TENSOR 3 CHIỀU (3-D TENSOR) ---
print("--- 3.4. 3-D Tensor ---")
tensor_3d = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("3D Tensor shape:", tensor_3d.shape)
print("-" * 30)

# --- 3.5. KIỂM TRA THÔNG TIN TENSOR ---
print("--- 3.5. Tensor Info ---")
print("Shape:", tensor_2d.shape)
print("Dtype:", tensor_2d.dtype)
print("Device (Chạy trên thiết bị nào):", tensor_2d.device)
print("-" * 30)

# --- 3.6. CHUYỂN ĐỔI GIỮA NUMPY VÀ TENSORFLOW ---
print("--- 3.6. TF <-> Numpy ---")
# Chuyển TF sang Numpy
ndarray = tensor_2d.numpy()
print("Chuyển sang Numpy:\n", ndarray)
# Chuyển Numpy ngược lại TF
tensor_from_numpy = tf.convert_to_tensor(ndarray)
print("-" * 30)

# --- 3.7. CÁC PHÉP TOÁN SỐ HỌC ---
print("--- 3.7. Arithmetic Operations ---")
x = tf.constant([1, 2])
y = tf.constant([3, 4])
print("Cộng:", tf.add(x, y))
print("Nhân từng phần tử:", tf.multiply(x, y))
print("-" * 30)

# --- 3.8. NHÂN MA TRẬN (MATRIX MULTIPLICATION) ---
print("--- 3.8. Matmul ---")
m1 = tf.constant([[1, 2], [3, 4]])
m2 = tf.constant([[5, 6], [7, 8]])
result_matmul = tf.matmul(m1, m2)
print("Kết quả nhân ma trận:\n", result_matmul)
print("-" * 30)

# --- 3.9. TẠO TENSOR NGẪU NHIÊN (RANDOM) ---
print("--- 3.9. Random Tensors ---")
# Ngẫu nhiên theo phân phối chuẩn (Normal Distribution)
random_normal = tf.random.normal(shape=(2, 2), mean=0.0, stddev=1.0)
print("Random Normal:\n", random_normal)
print("-" * 30)

# --- 3.10. BIẾN ĐỔI HÌNH DẠNG (RESHAPE) ---
print("--- 3.10. Reshape ---")
original = tf.constant([1, 2, 3, 4, 5, 6])
reshaped = tf.reshape(original, (2, 3))
print("Original 1D:", original)
print("Reshaped to 2x3:\n", reshaped)

# --- 3.11. BIẾN ĐỔI HÌNH DẠNG (RESHAPE) ---
print("--- 3.11. Reshape ---")

--- 3.1. Scalar (0-D Tensor) ---
Scalar: tf.Tensor(4, shape=(), dtype=int32)
------------------------------
--- 3.2. Vector (1-D Tensor) ---
Vector: tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
------------------------------
--- 3.3. Matrix (2-D Tensor) ---
Matrix:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
------------------------------
--- 3.4. 3-D Tensor ---
3D Tensor shape: (2, 2, 2)
------------------------------
--- 3.5. Tensor Info ---
Shape: (3, 2)
Dtype: <dtype: 'int32'>
Device (Chạy trên thiết bị nào): /job:localhost/replica:0/task:0/device:CPU:0
------------------------------
--- 3.6. TF <-> Numpy ---
Chuyển sang Numpy:
 [[1 2]
 [3 4]
 [5 6]]
------------------------------
--- 3.7. Arithmetic Operations ---
Cộng: tf.Tensor([4 6], shape=(2,), dtype=int32)
Nhân từng phần tử: tf.Tensor([3 8], shape=(2,), dtype=int32)
------------------------------
--- 3.8. Matmul ---
Kết quả nhân ma trận:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
--------